### PR TITLE
Notification when someone chooses a tool

### PR DESCRIPTION
**Pull request by RickRollMaster101**

### CODE REVIEW

**Comment by agam778** [comment]
Well, as it is a terminal tool, won't it be better to keep it terminal-only?
Also will this work on VPS etc (or basically without a window/desktop manager)?

**Comment by RickRollMaster101** [comment]
eh probably not

**Comment by RickRollMaster101** [comment]
but most people are using this in a wm/de

**Comment by agam778** [comment]
Wait I'll test it in my azure VPS once

**Comment by agam778** [comment]
Yeah just tested.
It doesn't notify in a VPS 😂

Merging the PR...

**Comment by RickRollMaster101** [comment]
pog

**Pull request merged**
